on: 
  workflow_dispatch:
    inputs:
      notebook:
        description: 'Submit a jupyter notebook to tira (expected to be in the notebooks directory)'
        required: true
        default: 'run-sparse-cross-encoder-4-512.ipynb'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.webis.de
          username: tira-user-fschlatt
          password: ${{ secrets.TIRA_DOCKER_REGISTRY_TOKEN }}
      -
        name: Set up Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      -
        name: Install required python packages
        run: |
          python -m pip install --upgrade pip
          pip install tira>=0.0.83
      -
        name: Set environment variables
        run: |
          echo "IMAGE_TAG=registry.webis.de/code-research/tira/tira-user-fschlatt/submission:${{ github.sha }}" >> $GITHUB_ENV
          echo "INPUT_DIRECTORY=${{ github.workspace }}/jupyter-notebook-submissions/example-ir-dataset/" >> $GITHUB_ENV
          echo "TIRA_JUPYTER_NOTEBOOK=${{ inputs.notebook }}" >> $GITHUB_ENV
          echo "TIRA_DOCKER_REGISTRY_TOKEN=${{ secrets.TIRA_DOCKER_REGISTRY_TOKEN }}" >> $GITHUB_ENV
          echo "TIRA_DOCKER_REGISTRY_USER=tira-user-fschlatt" >> $GITHUB_ENV
          echo "TIRA_CLIENT_TOKEN=${{ secrets.TIRA_CLIENT_TOKEN }}" >> $GITHUB_ENV
          echo "TIRA_CLIENT_USER=${{ secrets.TIRA_CLIENT_USER }}" >> $GITHUB_ENV
          echo "TIRA_TASK_ID=ir-benchmarks" >> $GITHUB_ENV
          echo "TIRA_CODE_REPOSITORY_ID=${{ secrets.TIRA_CODE_REPOSITORY_ID }}" >> $GITHUB_ENV
          echo "TIRA_VM_ID=fschlatt" >> $GITHUB_ENV 
          tira-run --export-submission-from-jupyter-notebook ${{ github.workspace }}/notebooks/${{ inputs.notebook }} >> $GITHUB_ENV
      - name: Build, test, and upload image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} --build-arg JUPYTER_NOTEBOOK=${{inputs.notebook}} ${{ github.workspace }}/notebooks
          tira-run --input-dataset workshop-on-open-web-search/re-ranking-20231027-training --image ${{ env.IMAGE_TAG }} --push true